import { useEffect } from "react";
import { useLocation } from "react-router-dom";
import { type Locale, useToolsLocale } from "../toolsLocale";

/** Public URL of the tools app; canonical links use it in every environment. */
export const toolsOrigin = "https://boypanjaitan.com/tools";

/** Social preview image generated by `scripts/prerender.mjs`. */
export function ogImageUrl(name: string) {
	return `${toolsOrigin}/og/${name}.png`;
}

/** Canonical URL for a router path, without a trailing slash except at the root. */
export function canonicalUrl(pathname: string) {
	const path = pathname.replace(/\/+$/, "");
	return path ? `${toolsOrigin}${path}` : `${toolsOrigin}/`;
}

const ogLocales: Record<Locale, string> = { en: "en_US", id: "id_ID" };

type PageMetaProps = {
	title: string;
	description: string;
	image?: string;
	imageAlt?: string;
	jsonLd?: object;
	noindex?: boolean;
};

function upsert(selector: string, create: () => HTMLElement) {
	let element = document.head.querySelector<HTMLElement>(selector);
	if (!element) {
		element = create();
		document.head.appendChild(element);
	}
	return element;
}

function setMeta(attribute: "name" | "property", key: string, content: string) {
	const element = upsert(`meta[${attribute}="${key}"]`, () => {
		const meta = document.createElement("meta");
		meta.setAttribute(attribute, key);
		return meta;
	});
	element.setAttribute("content", content);
}

function removeMeta(attribute: "name" | "property", key: string) {
	document.head.querySelector(`meta[${attribute}="${key}"]`)?.remove();
}

export function PageMeta({
	title,
	description,
	image,
	imageAlt,
	jsonLd,
	noindex = false,
}: PageMetaProps) {
	const { pathname } = useLocation();
	const { locale } = useToolsLocale();

	useEffect(() => {
		const url = canonicalUrl(pathname);
		document.title = title;
		setMeta("name", "description", description);
		upsert('link[rel="canonical"]', () => {
			const link = document.createElement("link");
			link.rel = "canonical";
			return link;
		}).setAttribute("href", url);

		setMeta("property", "og:type", "website");
		setMeta("property", "og:site_name", "Boy's tools");
		setMeta("property", "og:title", title);
		setMeta("property", "og:description", description);
		setMeta("property", "og:url", url);
		setMeta("property", "og:locale", ogLocales[locale]);
		setMeta("name", "twitter:title", title);
		setMeta("name", "twitter:description", description);
		setMeta("name", "twitter:card", image ? "summary_large_image" : "summary");
		if (image) {
			setMeta("property", "og:image", image);
			setMeta("property", "og:image:width", "1200");
			setMeta("property", "og:image:height", "630");
			setMeta("property", "og:image:alt", imageAlt ?? title);
			setMeta("name", "twitter:image", image);
		} else {
			for (const key of [
				"og:image",
				"og:image:width",
				"og:image:height",
				"og:image:alt",
			])
				removeMeta("property", key);
			removeMeta("name", "twitter:image");
		}
		if (noindex) setMeta("name", "robots", "noindex");
		else removeMeta("name", "robots");

		const script = document.head.querySelector("#page-jsonld");
		if (jsonLd) {
			upsert("#page-jsonld", () => {
				const element = document.createElement("script");
				element.id = "page-jsonld";
				element.setAttribute("type", "application/ld+json");
				return element;
			}).textContent = JSON.stringify(jsonLd);
		} else {
			script?.remove();
		}
	}, [description, image, imageAlt, jsonLd, locale, noindex, pathname, title]);

	return null;
}
